---
- name: Create and start the build container.
  containers.podman.podman_container:
    image: "{{ dev_container_from_image }}"
    name: "{{ dev_container_name }}"
    command: "tail -f /dev/null"
    state: started

- name: Add new container to the inventory
  ansible.builtin.add_host:
    hostname: "{{ dev_container_name }}"
    ansible_connection: podman
    ansible_python_interpreter: /usr/bin/python3

- name: Ensure Python is installed.
  ansible.builtin.raw: pacman -Syu --noconfirm {{ dev_container_python_package }}
  delegate_to: "{{ dev_container_name }}"
  changed_when: true

- name: Gather facts inside the container.
  ansible.builtin.setup:
  delegate_to: "{{ dev_container_name }}"

- name: Run pacman -Syu.
  become: true
  community.general.pacman:
    update_cache: true
    upgrade: true

- name: Install required packages.
  community.general.pacman:
    name: "{{ dev_container_packages }}"
  delegate_to: "{{ dev_container_name }}"

- name: Ensure locale is correct.
  delegate_to: "{{ dev_container_name }}"
  block:
    - name: Install locales.
      become: true
      community.general.locale_gen:
        name: "{{ item }}"
        state: present
      loop: "{{ dev_container_locales }}"
  rescue:
    - name: Remove NoExtract directive from pacman.conf.
      ansible.builtin.lineinfile:
        path: /etc/pacman.conf
        regex: "^NoExtract"
        state: absent

    - name: Force reinstallation of glibc to generate missing locale.
      become: true
      ansible.builtin.command:
        cmd: "pacman -Sy --noconfirm glibc"
      changed_when: false

    - name: Install locales.
      become: true
      community.general.locale_gen:
        name: "{{ item }}"
        state: present
      loop: "{{ dev_container_locales }}"

- name: Commit the container.
  ansible.builtin.command: >
    podman commit {{ dev_container_name }} {{ dev_container_image_name }}
  changed_when: true

- name: Remove the container.
  containers.podman.podman_container:
    name: "{{ dev_container_name }}"
    state: absent
