---
- name: Prepare
  hosts: all

  tasks:
    - name: Enable epel.
      become: true
      ansible.builtin.dnf:
        name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm
        state: present
